version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: fundamentos01-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fundamentos01-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://192.168.64.1:5432/devdb
      DB_USERNAME: ups
      DB_PASSWORD: ups123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "false"
      JWT_SECRET: mySecretKeyForJWT2024MustBeAtLeast256BitsLongForHS256Algorithm
      JWT_EXPIRATION: "1800000"
      JWT_REFRESH_EXPIRATION: "604800000"
      JWT_ISSUER: fundamentos01-api
      ROOT_LOG_LEVEL: WARN
      APP_LOG_LEVEL: INFO
      TZ: America/Guayaquil
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - fundamentos-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  fundamentos-network:
    driver: bridge